### ISSUE TITLE
Minecraft Dig Server Crash

### ISSUE THREAD

**Issue by Bokyubi** [KonoTyran/Minecraft_AP_Randomizer#17]
### What happened?

When you move scaffolding in your inventory, the server will just crash

### Discord Username

Bokyubi#0730

### Manual Minecraft Launch?

- [ ] Manual Launch

### Version

Minecraft Server (Default)

**Comment by KonoTyran** [comment]
Minecraft Dig served its purpose. I have no plans on working on it further. it was a one time April 1st joke.
