### ISSUE TITLE
[Bug]: Brief Description of bug here

### ISSUE THREAD

**Issue by TimoteeBaboulin** [KonoTyran/Minecraft_AP_Randomizer#18]
### What happened?

Description of the bug:
For some reason all type of mining or interacting isn't working
I can not break blocks (tho I can break items like grass)
I can not open/close doors or similar items (tho I can use crafting tables or chests)

I have tried to find if that was a feature of the randomizer, but couldn't find any information about unlocking mining

### Discord Username

TheMoonBeard

### Manual Minecraft Launch?

- [ ] Manual Launch

### Version

Archipelago Minecraft Client

**Comment by KonoTyran** [comment]
The mod is server side only, do not install it on your client.
