### ISSUE TITLE
[Bug]: Server crashing when entities spawn in

### ISSUE THREAD

**Issue by chester-fields** [KonoTyran/Minecraft_AP_Randomizer#34]
### What happened?

Hi there, first off just want to say thank you for all the work you've put into this! This is my first experience with randomizers/multiworlds and I'm loving it. 

I joined a friends multiworld last night, which is intended to last throughout this entire week. Everything worked great last night playing for a few hours. Today when opening minecraft back up I experienced a server crash within about 20-30 seconds of getting onto the server. 

I've tried a few things to try and assist with troubleshooting:
-Set server's render distance to 1. This allowed me to be stable because I wasn't spawning in any entities. I then walked around a little and crashed when a zombie loaded in nearby.

-Removed the aprandomizer jar file from the mod folder within the archipelago world folder. This allowed me to be stable as well, which led me to believe the randomizer is the source of the issue.

-Checked the server crash reports. This confirmed my suspicions of the randomizer being the culprit. I'll attach a few of the crash reports here so you can have full context. It seems like each of the crashes a different entity is causing it depending on where I am. It seems to stem from the OnLivingHurt event but I'm not positive on that, so maybe you can provide some clarity there.

Hopefully this is something resolveable, I'd love to continue playing this world this week but if it's something that's not possible to fix I'll have to ask the game host to release all my checks to others.

Thanks for your help!

[crash-2024-09-16_12.38.29-server.txt](https://github.com/user-attachments/files/17016693/crash-2024-09-16_12.38.29-server.txt)
[crash-2024-09-16_12.24.35-server.txt](https://github.com/user-attachments/files/17016694/crash-2024-09-16_12.24.35-server.txt)
[crash-2024-09-16_12.20.21-server.txt](https://github.com/user-attachments/files/17016695/crash-2024-09-16_12.20.21-server.txt)
[crash-2024-09-16_11.40.29-server.txt](https://github.com/user-attachments/files/17016696/crash-2024-09-16_11.40.29-server.txt)

### Discord Username

chesterfields

### Manual Minecraft Launch?

- [ ] Manual Launch

### Version

Minecraft Server (Default)

### Relevant log output

```shell
https://github.com/user-attachments/files/17016693/crash-2024-09-16_12.38.29-server.txt
https://github.com/user-attachments/files/17016694/crash-2024-09-16_12.24.35-server.txt
https://github.com/user-attachments/files/17016695/crash-2024-09-16_12.20.21-server.txt
https://github.com/user-attachments/files/17016696/crash-2024-09-16_11.40.29-server.txt
```

**Comment by KonoTyran** [comment]
Looks like its complain about not being able to read slot data when an entity dies. Fix for now is to make sure you are connected to an AP server before you join. Use the `/connect` command in the console before joining the server with your minecraft client.

**Comment by chester-fields** [comment]
This works great, thanks for the quick reply and solution. Very much appreciated!
