### ISSUE TITLE
[Bug]: End city failed to spawn

### ISSUE THREAD

**Issue by Intrinity-37** [KonoTyran/Minecraft_AP_Randomizer#4]
### What happened?

Tested on 0.3.0 RC2.

Just played a seed where an End City was supposed to spawn in the Nether, but the structure did not exist despite the compass pointing to its location. /locate states that it could not find that type of structure nearby.
![2022-04-23_23 55 57](https://user-images.githubusercontent.com/28081085/164955900-a0bfe81b-536a-41d4-963c-7c632edb36e4.png)
![2022-04-23_23 56 01](https://user-images.githubusercontent.com/28081085/164955903-c2ca4d72-3cbc-46f3-a968-7b54e03c9d15.png)

All other structures seemed to have spawned just fine

Archipelago room: https://archipelago.gg/room/vg_e5vXZTrmYtHykCRiGlg
Relevant APMC: https://archipelago.gg/slot_file/vg_e5vXZTrmYtHykCRiGlg/4
 

### Discord Username

Kippi00#3254

### Manual Minecraft Launch?

- [X] Manual Launch

### Version

Minecraft Server (Default)

**Comment by KonoTyran** [comment]
Did all end cities fail to spawn in the nether, or just this one location?

**Comment by Intrinity-37** [comment]
All end cities seemed to have failed to spawn. i've tried going out as far as i can (even at about 4k blocks about) but the compass will not point to any other one updating it and /locate still says there is no structure nearby

Also to make sure, i've looked at the APMC file and there is indeed supposed to be an end city in the nether
