### ISSUE TITLE
[Bug]: fix MC35

### ISSUE THREAD

**Issue by KonoTyran** [KonoTyran/Minecraft_AP_Randomizer#8]
### What happened?

Had to break mc35 to make 1.19 work, need to fix mc35

### Manual Minecraft Launch?

- [ ] Manual Launch

### Version

Minecraft Server (Default)

**Comment by ThePhar** [comment]
And here I was about to make the report.
![image](https://user-images.githubusercontent.com/11338376/174398299-cf2d0ad6-495c-40d5-aa1b-1bdd253922b1.png)

Smh my head
